version: "2"
checks:
  argument-count:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30
exclude_patterns:
  - "dist/"
  - "docs/"
  - "src/eager/"
  - "**/node_modules/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "karma.conf.js"
