version: "2"
checks:
  method-lines:
    config:
      threshold: 30
exclude_patterns:
  - "dist/"
  - "docs/"
  - "**/node_modules/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "karma.conf.js"
