name: Docs CD Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'docs-src/**'

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --config docs-src/fly.toml --dockerfile docs-src/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
