name: Landing CD Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'landing/**'

jobs:
  deploy:
    name: Deploy Landing Site
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: wyvox/action-setup-pnpm@v3
      - name: Install Dependencies
        run: pnpm install
      - name: Build JS package
        run: pnpm -F shepherd.js build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --config landing/fly.toml --dockerfile landing/Dockerfile --build-secret PUBLIC_SHEPHERD_PUBLIC_KEY=${{ secrets.PUBLIC_SHEPHERD_PUBLIC_KEY }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
