name: Publish Github Pages

on:
  push:
    tags:
      - v*

jobs:
  delpoy:
    # Job name is Greeting
    name: Deploy Site
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Deps and Build
        run: |
          pnpm i
          pnpm build
      - name: Build docs
        run: pnpm docs
      - name: Publish site and docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: true
          cname: shepherdjs.dev
