name: Test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test-lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: wyvox/action-setup-pnpm@v3

      # Install project dependencies
      - name: Install dependencies and run linting
        run: pnpm install && pnpm lint:js

  test-unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: wyvox/action-setup-pnpm@v3

      - name: Install Dependencies
        run: pnpm install

      # Run Jest
      - name: Run Unit Tests
        run: pnpm test:unit:ci

  #       - name: Publish code coverage
  #         uses: paambaati/codeclimate-action@v2.7.4
  #         env:
  #           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  test-integration:
    name: Run Integration Chrome Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('examples/basic-pnpm/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies and setup Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: pnpm build
          start: pnpm test:cy:start-server

  automerge:
    needs: [test-unit, test-integration]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
